// USERS
export const GET_USER = "GET_USER";
export const PATCH_USER = "PATCH_USER";
export const PATH_USER_LANGUAGE = "PATH_USER_LANGUAGE";
export const VERIFY_USER = "VERIFY_USER";

// KINDERGARTENS
export const KINDERGARTENS_GETALL = "KINDERGARTENS_GETALL";
export const KINDERGARTENS_GET_ONE = "KINDERGARTENS_GETONE";

// FAVORITE
export const FAVORITE_GETALL = "FAVORITE_GETALL";
export const FAVORITE_DELETE = "FAVORITE_DELETE";
export const FAVORITE_CREATE = "FAVORITE_CREATE";

// PAYMENT
export const PAYMENT_GETALL = "PAYMENT_GETALL";
export const PAYMENT_GET_ONE = "PAYMENT_GET_ONE";
export const PAYMENT_CREATE = "PAYMENT_CREATE";
export const PAYMENT_GET_BY_UUID = "PAYMENT_GET_BY_UUID";

// BY_ACCAUNT
export const BY_ACCAUNT_CREATE = "BY_ACCAUNT_CREATE";

// FEEDBACK
export const FEEDBACK_CREATE = "FEEDBACK_CREATE";
export const MEDIA_CREATE = "MEDIA_CREATE";

// REGIONS
export const REGIONS_GET = "REGIONS_GET";

// APPLICATIONS
export const APPLICATIONS_GETALL = "APPLICATIONS_GETALL";
export const APPLICATIONS_CREATE = "APPLICATIONS_CREATE";
export const APPLICATIONS_GET_BY_UUID = "APPLICATIONS_GET_BY_UUID";
